### ISSUE TITLE
Can't add an account

### ISSUE THREAD

**Issue by grootstebozewolf** [speckleworks/SpeckleBlender#10]
Branch: 2.80
Docker version: 2.81.1
Console output:

Traceback (most recent call last):
  File "C:\Users\908441\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons_contrib\bpy_speckle\operators\accounts.py", line 62, in execute
    client.server = self.server
  File "C:/org/blender/blender/release/scripts\modules\bpy_types.py", line 676, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'SpeckleAddAccount' object has no attribute 'server'

location: <unknown location>:-1

location: <unknown location>:-1

Settings:
![image](https://user-images.githubusercontent.com/2713718/62368660-86b9f380-b52d-11e9-8baf-46dbd7f2d0d3.png)

Steps to reproduce:
Install Blender from source
run cmd prompt
run commands
````
python -m ensurepip
python -m pip install pip --upgrade
python -m pip install speckle
````
 from python/bin of blender

Place bpy_speckle under C:\Users\......\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons_contrib\bpy_speckle
Change version of blender in __init__.py

**Comment by tsvilans** [comment]
Fixed in commit 482073fefba5306d4e4a5bd0008c33ac5d3f8e79.
