### ISSUE TITLE
Failure to connect

### ISSUE THREAD

**Issue by rgsouthall** [speckleworks/SpeckleBlender#14]
Hi.
It appears I can login to the hestia server via a web browser but when I use the same credentials in the Blender (2.82) tab on Windows 10 I get the error message below.
On Linux a gcc error prevents the speckle module from being built. Is the addon known to work on Linux?
Cheers
Ryan

Error: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bpy_speckle\operators\accounts.py", line 38, in execute
    _add_account(client, cache, self.email, self.pwd, self.host, "Speckle Hestia")
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bpy_speckle\functions.py", line 116, in _add_account
    cache.write_account(host, host_name, email, authtoken)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\modules\speckle\Cache.py", line 165, in write_account
    raise Exception("Failed to connect to database.")
Exception: Failed to connect to database.

**Comment by tsvilans** [comment]
Can you tell me what does this evaluate to: 
`os.path.join(os.getenv('LOCALAPPDATA'), os.path.join('SpeckleSettings', 'SpeckleCache.db'))`?

Try creating the directory returned by `os.path.join(os.getenv('LOCALAPPDATA'), 'SpeckleSettings'` manually. It tries to create or connect to a database there and it's failing.

**Comment by tsvilans** [comment]
I realized you probably won't get anything meaningful from `os.getenv('LOCALAPPDATA')` as I believe that only works for Windows...

Pinging @didimitrie : what are the correct folders on Linux and Mac for SpeckleSettings and the user database?

**Comment by rgsouthall** [comment]
Creating the SpeckleSettings folder did the trick on Windows 10. 
Should the creation of this folder also solve the gcc problem on Linux?
Cheers
Ryan

**Comment by tsvilans** [comment]
I think so, since there is no actual compilation that goes on. We just haven't set any default cache directories.

It was never a problem because there was already an existing `SpeckleSettings` folder and a `SpeckleCache.db` from the Rhino client 😛 

Anyway, that's on the to-do list. I'm not a Linux user: what would be the "equivalent" of the %APPDATA% folder on Linux?

**Comment by rgsouthall** [comment]
Don't think there is one. Different Linux distributions have different
ideas on this. Common places are /home/*user*/.config/ or
/home/*user*/.local/share/
but I don't think Python makes a call on this by default. I have tried
setting the LOCALAPPDATA entry within os.environ to /home/ryan/.config/ by
inserting the code into your install_dependencies file. I also
created the SpeckleSettings folder within it. A LOCALAPPDATA entry is
created but I get the same error as below:


Speckle not found. Attempting to install dependencies...
Installing speckle to
/home/ryan/.config/blender/2.82/scripts/addons/modules...
WARNING: Target directory
/home/ryan/.config/blender/2.82/scripts/addons/modules/pydantic-1.4.di
st-info already exists. Specify --upgrade to force replacement.

WARNING: Target directory
/home/ryan/.config/blender/2.82/scripts/addons/modules/pydantic alread
y exists. Specify --upgrade to force replacement.

ERROR: pylint 2.4.4 has requirement astroid<2.4,>=2.3.0, but you'll have
astroid 2.2.5 which is
incompatible.


   ERROR: Command errored out with exit status 1:
    command: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'/tm
p/pip-install-yllwukw_/typed-ast/setup.py'"'"';
__file__='"'"'/tmp/pip-install-yllwukw_/typed-as
t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
open)(__file__);code=f.read().replace('"'"'\
r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' install --recor
d /tmp/pip-record-fhm3aaap/install-record.txt
--single-version-externally-managed --home /tmp/pi
p-target-dlxe86b_ --compile --install-headers
/tmp/pip-target-dlxe86b_/include/python/typed-ast
        cwd: /tmp/pip-install-yllwukw_/typed-ast/

   Complete output (67 lines):

   running install


   running build


   running build_py

   creating build


   creating build/lib.linux-x86_64-3.8

   creating build/lib.linux-x86_64-3.8/typed_ast

   copying typed_ast/conversions.py -> build/lib.linux-x86_64-3.8/typed_ast

   copying typed_ast/ast3.py -> build/lib.linux-x86_64-3.8/typed_ast

   copying typed_ast/ast27.py -> build/lib.linux-x86_64-3.8/typed_ast

   copying typed_ast/__init__.py -> build/lib.linux-x86_64-3.8/typed_ast

   package init file 'ast3/tests/__init__.py' not found (or not a regular
file)
   creating build/lib.linux-x86_64-3.8/typed_ast/tests

   copying ast3/tests/test_basics.py ->
build/lib.linux-x86_64-3.8/typed_ast/tests
   running build_ext

   building '_ast27' extension

   creating build/temp.linux-x86_64-3.8

   creating build/temp.linux-x86_64-3.8/ast27

   creating build/temp.linux-x86_64-3.8/ast27/Parser

   creating build/temp.linux-x86_64-3.8/ast27/Python

   creating build/temp.linux-x86_64-3.8/ast27/Custom

   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/acceler.c -o
build/temp.linux-x86_64-3.8/ast27/Par
ser/acceler.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/bitset.c -o
build/temp.linux-x86_64-3.8/ast27/Pars
er/bitset.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/grammar.c -o
build/temp.linux-x86_64-3.8/ast27/Par
ser/grammar.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/grammar1.c -o
build/temp.linux-x86_64-3.8/ast27/Pa
rser/grammar1.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/node.c -o
build/temp.linux-x86_64-3.8/ast27/Parser
/node.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/parser.c -o
build/temp.linux-x86_64-3.8/ast27/Pars
er/parser.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/parsetok.c -o
build/temp.linux-x86_64-3.8/ast27/Pa
rser/parsetok.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Parser/tokenizer.c -o
build/temp.linux-x86_64-3.8/ast27/P
arser/tokenizer.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Python/asdl.c -o
build/temp.linux-x86_64-3.8/ast27/Python
/asdl.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Python/ast.c -o
build/temp.linux-x86_64-3.8/ast27/Python/
ast.o


   ast27/Python/ast.c: In function ‘ast_for_print_stmt’:

   ast27/Python/ast.c:2432:9: warning: this ‘if’ clause does not guard...
[-Wmisleading-indenta
tion]


    2432 |         if (!dest)

         |         ^~

   ast27/Python/ast.c:2434:13: note: ...this statement, but the latter is
misleadingly indented
as if it were guarded by the ‘if’

    2434 |             start = 4;

         |             ^~~~~

   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Python/graminit.c -o
build/temp.linux-x86_64-3.8/ast27/Py
thon/graminit.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Python/mystrtoul.c -o
build/temp.linux-x86_64-3.8/ast27/P
ython/mystrtoul.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Python/Python-ast.c -o
build/temp.linux-x86_64-3.8/ast27/
Python/Python-ast.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast27/Inc
lude -I/usr/include/python3.8 -c ast27/Custom/typed_ast.c -o
build/temp.linux-x86_64-3.8/ast27/C
ustom/typed_ast.o


   gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
-fno-semantic-interpo
sition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -O3 -march=znver1
build/temp.linux-x86_
64-3.8/ast27/Parser/acceler.o
build/temp.linux-x86_64-3.8/ast27/Parser/bitset.o build/temp.linux
-x86_64-3.8/ast27/Parser/grammar.o
build/temp.linux-x86_64-3.8/ast27/Parser/grammar1.o build/tem
p.linux-x86_64-3.8/ast27/Parser/node.o
build/temp.linux-x86_64-3.8/ast27/Parser/parser.o build/t
emp.linux-x86_64-3.8/ast27/Parser/parsetok.o
build/temp.linux-x86_64-3.8/ast27/Parser/tokenizer.
o build/temp.linux-x86_64-3.8/ast27/Python/asdl.o
build/temp.linux-x86_64-3.8/ast27/Python/ast.o
build/temp.linux-x86_64-3.8/ast27/Python/graminit.o
build/temp.linux-x86_64-3.8/ast27/Python/my
strtoul.o build/temp.linux-x86_64-3.8/ast27/Python/Python-ast.o
build/temp.linux-x86_64-3.8/ast2
7/Custom/typed_ast.o -L/usr/lib -o
build/lib.linux-x86_64-3.8/typed_ast/_ast27.cpython-38-x86_64
-linux-gnu.so


   building '_ast3' extension

   creating build/temp.linux-x86_64-3.8/ast3

   creating build/temp.linux-x86_64-3.8/ast3/Parser

   creating build/temp.linux-x86_64-3.8/ast3/Python

   creating build/temp.linux-x86_64-3.8/ast3/Custom

   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/acceler.c -o
build/temp.linux-x86_64-3.8/ast3/Parser
/acceler.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/bitset.c -o
build/temp.linux-x86_64-3.8/ast3/Parser/
bitset.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/grammar.c -o
build/temp.linux-x86_64-3.8/ast3/Parser
/grammar.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/grammar1.c -o
build/temp.linux-x86_64-3.8/ast3/Parse
r/grammar1.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/node.c -o
build/temp.linux-x86_64-3.8/ast3/Parser/no
de.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/parser.c -o
build/temp.linux-x86_64-3.8/ast3/Parser/
parser.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/parsetok.c -o
build/temp.linux-x86_64-3.8/ast3/Parse
r/parsetok.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Parser/tokenizer.c -o
build/temp.linux-x86_64-3.8/ast3/Pars
er/tokenizer.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Python/asdl.c -o
build/temp.linux-x86_64-3.8/ast3/Python/as
dl.o


   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3
-Wall -march=x86-64 -
mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64
-mtune=generic -O3 -p
ipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -O3
-march=znver1 -fPIC -Iast3/Incl
ude -I/usr/include/python3.8 -c ast3/Python/ast.c -o
build/temp.linux-x86_64-3.8/ast3/Python/ast
.o


   ast3/Python/ast.c:22:1: error: conflicting types for
‘_PyObject_FastCall’
      22 | _PyObject_FastCall(PyObject *func, PyObject *const *args, int
nargs)
         | ^~~~~~~~~~~~~~~~~~

   In file included from /usr/include/python3.8/abstract.h:837,

                    from /usr/include/python3.8/Python.h:147,

                    from ast3/Python/ast.c:6:

   /usr/include/python3.8/cpython/abstract.h:145:1: note: previous
definition of ‘_PyObject_Fas
tCall’ was here


     145 | _PyObject_FastCall(PyObject *func, PyObject *const *args,
Py_ssize_t nargs)
         | ^~~~~~~~~~~~~~~~~~

   error: command 'gcc' failed with exit status 1

   ----------------------------------------

ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c
'import sys, setuptools,
tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-yllwukw_/typed-ast/setup.py'"'"'; __file__='"'"'/
tmp/pip-install-yllwukw_/typed-ast/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__fil
e__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' install --record
/tmp/pip-record-fhm3aaap/install-record.txt --single-version-
externally-managed --home /tmp/pip-target-dlxe86b_ --compile
--install-headers /tmp/pip-target-d
lxe86b_/include/python/typed-ast Check the logs for full command output.

Traceback (most recent call last):
 File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351,
in enable
   mod = __import__(module_name)
 File
"/home/ryan/.config/blender/2.82/scripts/addons/bpy_speckle/__init__.py",
line 53, in <mo
dule>
   from speckle import SpeckleApiClient, SpeckleCache
ModuleNotFoundError: No module named 'speckle'

**Comment by tsvilans** [comment]
> Don't think there is one. Different Linux distributions have different ideas on this. Common places are /home/*user*/.config/ or /home/*user*/.local/share/ but I don't think Python makes a call on this by default. I have tried setting the LOCALAPPDATA entry within os.environ to /home/ryan/.config/ by inserting the code into your install_dependencies file. I also created the SpeckleSettings folder within it. A LOCALAPPDATA entry is created but I get the same error as below:

In this case, LOCALAPPDATA would have to be set when booting up Blender, as it is called when the PySpeckle client tries to access the local Speckle database during runtime. But we do need to put in proper platform specific default cache locations. Could be anywhere, it just needs to be agreed upon.

I'm not sure what's happening with your compilation issues... looks like a problem with `typed_ast` but also looks like there is a mismatch between Python versions... I see `/usr/include/python3.8` but AFAIK Blender is still using Python 3.7.4, which might be a source of the problem...

**Comment by tsvilans** [comment]
Could you try deleting everything in `/home/ryan/.config/blender/2.82/scripts/addons/modules` and type this into the Blender Python console, line by line:

```
import os, subprocess
modulespath = os.path.normpath(os.path.join(bpy.utils.script_path_user(),"addons","modules"))
res = subprocess.run([bpy.app.binary_path_python, "-m", "pip", "install", "-t", "{}".format(modulespath), "--no-deps", "pydantic"])
res = subprocess.run([bpy.app.binary_path_python, "-m", "pip", "install", "-t", "{}".format(modulespath), "speckle"])
```

**Comment by rgsouthall** [comment]
Success.
On Arch Linux when you install Blender through in-built mechanisms it uses the system Python version, which for me is 3.8. If you download Blender from the Foundation for Linux it comes with Python 3.7. The mismatch between my system Python and your Python seems to be the problem as the downloaded Blender works fine and the cache file is created in /home/ryan/.config/SpeckeSettings.
Logging into the hesta server worked too.
I have just seen your last post and will see if forcing the system Python version for pip install works on my built-in install.
Look forward to trying Speckle out.
Ryan

**Comment by tsvilans** [comment]
Great! Glad it got sorted out. Ideally, we want to have this running cross-platform, so keep the test cases coming.
