### ISSUE TITLE
Problem with 'Add Account'

### ISSUE THREAD

**Issue by ifcwebserver** [speckleworks/SpeckleBlender#16]
For anyone who is trying to play with SpeckleBlender ( Version 2.8)

If you failed to add your account and got an error message "Failed to connect to database." in Cache.py line 165
All what you have to do it to create a folder "SpeckleSettings" at this location:
C:\Users\YOUR_USER_NAME\AppData\Local\SpeckleSettings

**Comment by CyrilWaechter** [comment]
Similarly on Linux you need to create a `SpeckleSettings` folder in your home folder ('mkdir ~/SpeckleSettings`). I will try to submit a PR to fix this issue which apparently is part of [PySpeckle](https://github.com/speckleworks/PySpeckle/blob/5a32fedeb061d2eff456bea5671dc1762af0a050/speckle/Cache.py#L55) not SpeckleBlender.

**Comment by tsvilans** [comment]
@ifcwebserver Yes, sorry, this fell off the truck since I've been testing it on a system that already has the Rhino Speckle client, therefore the `SpeckleSettings` folder already exists :) 

@CyrilWaechter has fixed this in PySpeckle.
