### ISSUE TITLE
Units not taken in account when importing geometries

### ISSUE THREAD

**Issue by CyrilWaechter** [speckleworks/SpeckleBlender#20]
Hi,

First of all. Thank you for all the work.

Just for record I noticed that units are not taken in account when you download objects. Steps to reproduce : 
1. Create a stream from Revit with length units set to millimeters and upload objects
2. Download objects in blender -> objects are 1000x too big

If you create a stream from Revit with units set to meters and upload objects then object have correct scale in blender (as blender default unit is also meter that sound logic).

I also noticed that length unit is correctly identified : 
![Units](https://user-images.githubusercontent.com/9622862/94943145-8ae9f400-04d7-11eb-85b6-ede7e37bd68a.png)
So it is just a matter of scaling the object but I don't know yet where in code this should be done.

**Comment by tsvilans** [comment]
It might be that the unit interpretation is case-sensitive, since sometimes it is `millimetres`, sometimes it is `Millimetres`, or even `millimeters` or `Millimeters`. I will take a look and see what the deal is... Could you show me the stream properties so we can rule that out?

**Comment by CyrilWaechter** [comment]
Sure. I created a simple wall millimetres based : [UNavZQjHm.zip](https://github.com/speckleworks/SpeckleBlender/files/5322881/UNavZQjHm.zip)
Recorded unit is `millimeters` as you can see.
For some other unit types I am not sure but for length unit I see no drawback to ignore case as I don't see any ambiguity.

**Comment by tsvilans** [comment]
Hi @CyrilWaechter, I've made it case-insensitive. Download the latest changes and let me know if that fixes things...

**Comment by CyrilWaechter** [comment]
I confirm that https://github.com/speckleworks/SpeckleBlender/commit/36500ec3125b573dd5d2fdb8f5df338252ae1139 fixed it. Thanks a lot !
