### ISSUE TITLE
TODO: Look at API for Blender 2.8 and assess any compatibility issues.

### ISSUE THREAD

**Issue by tsvilans** [speckleworks/SpeckleBlender#8]

**Comment by afomi** [comment]
I've started to poke at this a little bit. Some of the APIs have changed. Can share a WIP branch.

Is there a test suite or QA process in place that might exercise the intended functionality? [Test](https://en.wikipedia.org/wiki/Integration_testing) breakages in 2.8 would indicate specifically what needs a look.

**Comment by tsvilans** [comment]
> I've started to poke at this a little bit. Some of the APIs have changed. Can share a WIP branch.
> 
> Is there a test suite or QA process in place that might exercise the intended functionality? [Test](https://en.wikipedia.org/wiki/Integration_testing) breakages in 2.8 would indicate specifically what needs a look.

No test suite yet. The 2.8 changes should mostly affect the interface, though I haven't tried it out yet. Contributions are always welcome! Shout if you need anything to be reviewed. It would probably be a good idea for me to make a separate branch for 2.8 too..
